import { useMemo,useState } from 'react';
import { assetUrl } from '../utils/assetUrl';
import StudentLayout from '../layouts/StudentLayout';
import StudentPageHeader from '../components/StudentPageHeader';
import AchievementBadge from '../components/AchievementBadge';
import { studentGoals } from '../data/mockData';
import { evaluateAchievements } from '../utils/achievementEngine';
import usePrototypeData from '../hooks/usePrototypeData';
import useFirestoreStudentProgress from '../hooks/useFirestoreStudentProgress';
import { useAuth } from '../auth/AuthContext';
const filters=[['all','All'],['unlocked','Unlocked'],['in_progress','In Progress'],['locked','Locked']];
export default function StudentAchievements(){const [filter,setFilter]=useState('all'),{user,profile}=useAuth(),data=usePrototypeData(),{assessmentsWithResults,overallPercentage,skillPercentages}=useFirestoreStudentProgress(),saved=user?.uid?data.goals?.[user.uid]:null,active=saved?{skill:saved.skill,current:saved.currentValue,target:saved.targetValue,status:saved.status}:null,student={id:user?.uid,name:profile?.displayName||'Student',gradeId:profile?.gradeId,avatarId:profile?.avatarId,overall:overallPercentage,skills:skillPercentages};const achievements=useMemo(()=>evaluateAchievements({student,assessments:assessmentsWithResults,results:assessmentsWithResults,goals:{current:active,history:[]}}),[user?.uid,overallPercentage,assessmentsWithResults,saved?.skill,saved?.currentValue,saved?.targetValue]);const visible=filter==='all'?achievements:achievements.filter(item=>item.status===filter);return <StudentLayout><div className="student-page subpage"><StudentPageHeader eyebrow="ACHIEVEMENTS" title="My trophy constellation" subtitle="Automatically calculated from your completed summative results."/><div className="collection-summary"><span><b>{achievements.filter(a=>a.status==='unlocked').length}</b> Unlocked</span><span><b>{achievements.filter(a=>a.status==='in_progress').length}</b> In progress</span><span><b>{achievements.filter(a=>a.status==='locked').length}</b> Locked</span></div><div className="achievement-filters">{filters.map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}<span>{value==='all'?achievements.length:achievements.filter(a=>a.status===value).length}</span></button>)}</div><section className="achievement-grid full-achievements">{visible.map(a=><AchievementBadge item={a} key={a.id}/>)}</section>{!visible.length&&<div className="panel empty-state"><img src={assetUrl('/assets/empty-states/empty-achievements.png')} alt=""/><p>No achievements unlocked yet.<br/>Keep going — your first badge is closer than you think!</p></div>}</div></StudentLayout>}
