import { useEffect,useState } from 'react';
import { CheckCircle2,Target } from 'lucide-react';
import StudentLayout from '../layouts/StudentLayout';
import StudentPageHeader from '../components/StudentPageHeader';
import Rocket from '../components/Rocket';
import { ProgressBar } from '../components/Progress';
import { studentGoals } from '../data/mockData';
import { prototypeStorage } from '../utils/prototypeStorage';
import usePrototypeData from '../hooks/usePrototypeData';
import { useAuth } from '../auth/AuthContext';
const skills=['Listening','Speaking','Reading','Writing'];
export default function StudentGoal(){const {user}=useAuth(),studentId=user?.uid,data=usePrototypeData(),goal=studentId?data.goals?.[studentId]||null:null;const [form,setForm]=useState({skill:'Writing',currentValue:68,targetValue:85});const [error,setError]=useState('');useEffect(()=>{if(goal)setForm({skill:goal.skill,currentValue:goal.currentValue,targetValue:goal.targetValue})},[goal]);const save=()=>{const current=Number(form.currentValue),target=Number(form.targetValue);if(current<0||current>100||target<0||target>100){setError('Results must be between 0 and 100%.');return}if(target<=current){setError('Target result must be higher than current result.');return}prototypeStorage.saveGoal({studentId,skill:form.skill,currentValue:current,targetValue:target,createdAt:new Date().toISOString(),status:'active'});setError('')};const progress=goal?Math.round(goal.currentValue/goal.targetValue*100):0;return <StudentLayout><div className="student-page subpage"><StudentPageHeader eyebrow="MY GOAL" title="My personal mission" subtitle="One focused step at a time."/>{goal&&<section className="panel goal-detail"><span className="goal-orbit"><Target size={34}/></span><div><span className="panel-kicker">CURRENT MISSION · {goal.status.toUpperCase()}</span><h2>{goal.skill} Goal</h2><p>Reach {goal.targetValue}% in {goal.skill}.</p><div className="goal-numbers"><strong>{goal.currentValue}%</strong><span>→</span><strong>{goal.targetValue}%</strong></div><ProgressBar value={progress}/><small>{progress}% of goal completed</small></div><Rocket/></section>}<section className="panel goal-editor"><div><span className="panel-kicker">{goal?'UPDATE GOAL':'CREATE GOAL'}</span><h2>{goal?'Adjust your mission':'Set your first goal'}</h2></div><div className="goal-form"><label>Choose skill<select value={form.skill} onChange={e=>setForm({...form,skill:e.target.value})}>{skills.map(skill=><option key={skill}>{skill}</option>)}</select></label><label>Current result<input type="number" min="0" max="100" value={form.currentValue} onChange={e=>setForm({...form,currentValue:e.target.value})}/></label><label>Target result<input type="number" min="0" max="100" value={form.targetValue} onChange={e=>setForm({...form,targetValue:e.target.value})}/></label><button className="primary" onClick={save}>Save goal</button></div>{error&&<p className="goal-error" role="alert">{error}</p>}</section><div className="section-heading"><div><span className="panel-kicker">GOAL HISTORY</span><h2>Missions accomplished</h2></div></div><section className="goal-history">{studentGoals.history.filter(item=>item.studentId===studentId).map(item=><article className="panel" key={item.id}><CheckCircle2 size={24}/><div><h3>{item.skill} Goal</h3><p>{item.start}% → {item.target}%</p><small>Reached {item.reached}% · {item.date}</small></div><span>{item.status}</span></article>)}</section></div></StudentLayout>}
