import { useState } from 'react';
import Modal from './Modal';
import { gradeOptions } from '../utils/gradeMapping';

const skillNames=['Listening','Speaking','Reading','Writing'];
const emptyForm=defaults=>({title:'',term:defaults.term||'Term 1',type:'summative',active:true,skills:{},classes:defaults.classes||['6b'],date:''});

export default function AssessmentModal({initial,defaults={},onClose,onSave}){
  const [form,setForm]=useState(initial?{...initial,skills:{...initial.skills},classes:[...initial.classes]}:emptyForm(defaults));
  const [errors,setErrors]=useState({});
  const [saving,setSaving]=useState(false);
  const selected=skill=>Object.prototype.hasOwnProperty.call(form.skills,skill);
  const toggleSkill=skill=>setForm(current=>{const skills={...current.skills};if(Object.prototype.hasOwnProperty.call(skills,skill))delete skills[skill];else skills[skill]='';return {...current,skills}});
  const validate=()=>{const next={};if(!form.title.trim())next.title='Enter an assessment title.';if(!form.term)next.term='Choose a Term.';if(!form.classes.length)next.classes='Choose at least one grade.';const chosen=Object.entries(form.skills);if(!chosen.length)next.skills='Choose at least one skill.';else if(chosen.some(([,max])=>max===''||!Number.isFinite(Number(max))||Number(max)<=0))next.skills='Enter a max score greater than 0 for every selected skill.';if(!form.date)next.date='Choose an assessment date.';setErrors(next);return Object.keys(next).length===0};
  const save=async()=>{if(!validate())return;setSaving(true);try{await onSave({...form,skills:Object.fromEntries(Object.entries(form.skills).map(([skill,max])=>[skill,Number(max)]))})}catch(error){console.error('Assessment save failed:',error);setErrors(current=>({...current,submit:'Unable to save this assessment. Please try again.'}));setSaving(false)}};
  return <Modal title={initial?'Edit assessment':'Create assessment'} onClose={onClose} footer={<><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':initial?'Save changes':'Create assessment'}</button></>}><div className="modal-form"><label>Title<input value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/>{errors.title&&<small className="form-error">{errors.title}</small>}</label><div className="form-grid"><label>Term<select value={form.term} onChange={event=>setForm({...form,term:event.target.value})}>{[1,2,3,4].map(number=><option key={number}>Term {number}</option>)}</select>{errors.term&&<small className="form-error">{errors.term}</small>}</label><label>Type<select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option value="summative">Summative Assessment</option><option value="term">Term Assessment</option></select></label></div><fieldset className="choice-field"><legend>Skills and maximum points</legend>{skillNames.map(skill=><label className="check-row" key={skill}><input type="checkbox" checked={selected(skill)} onChange={()=>toggleSkill(skill)}/><span>{skill}</span><input type="number" min="1" max="100" disabled={!selected(skill)} value={form.skills[skill]??''} onChange={event=>setForm({...form,skills:{...form.skills,[skill]:event.target.value}})} placeholder="Max points"/></label>)}{errors.skills&&<small className="form-error">{errors.skills}</small>}</fieldset><fieldset className="choice-field"><legend>Grades</legend><div className="choice-grid">{gradeOptions.map(item=><label className="check-row" key={item.legacyId}><input type="checkbox" checked={form.classes.includes(item.legacyId)} onChange={()=>setForm({...form,classes:form.classes.includes(item.legacyId)?form.classes.filter(id=>id!==item.legacyId):[...form.classes,item.legacyId]})}/>{item.label}</label>)}</div>{errors.classes&&<small className="form-error">{errors.classes}</small>}</fieldset><label>Date<input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/>{errors.date&&<small className="form-error">{errors.date}</small>}</label>{errors.submit&&<p className="form-error">{errors.submit}</p>}</div></Modal>;
}
